### ISSUE TITLE
Quem são as empresas envolvidas?

### ISSUE THREAD

**Issue by yurigabrich** [rio-covid-19/rio-covid-19.github.io#38]
- [x] Levantar o nome, site e tipo de participação de cada empresa.
- [x] Organizar as empresas por categorias, como organização, parceria, financiamento e apoio.
- [x] Montar o *grid* de visualização das logos das empresas ~~envolvidas em `_posts > partners`~~, conforme descrito em #40 .

**Comment by thomascampello** [comment]
Organização
**CEFET** - @cefet_rj - http://www.cefet-rj.br/index.php - https://drive.google.com/drive/folders/1QCAqleTHuSEgIbxrZT9CcennfaGoOQP1?usp=sharing

**Secretaria Municipal de Saúde do RJ** - @saude_rio - http://www.rio.rj.gov.br/web/sms - https://drive.google.com/file/d/1uqeJYkOce4oxR1VPj2U13dAOh0QL9KoP/view?usp=sharing

**Seção Rio**

Financiamento
**IEEE HAC** - - https://hac.ieee.org/ - https://drive.google.com/file/d/1j_vV_xGis1QyZkGlZw5MPSI_XJ7HZYjH/view?usp=sharing

Parceiras
**YP Rio** - - https://www.facebook.com/ieee.yp.rio/?tn-str=k*F - https://drive.google.com/file/d/1XmuuaVAIChl3o0LL2fxGfY560r0nKYox/view?usp=sharing
**Furnas** - @furnasenergia - https://www.furnas.com.br/ - https://drive.google.com/file/d/1xrKG9i0a6KdanOHUuPvyd7OhNWiZjdxX/view?usp=sharing
**White Martins** - https://www.linkedin.com/company/white-martins/ - http://www.praxair.com.br/ - https://drive.google.com/file/d/1aSsbGRiwimZFcZxi2i6Zi1Ziwg1BhNaL/view?usp=sharing
**Gsol** - - https://www.gsol.com.br/ - https://drive.google.com/file/d/1csfE44BLLoTzK2Rp0EAuvsVAThCX6rrD/view?usp=sharing
**Ezrezt** - - https://covid.ezrest.com.br/#home - https://drive.google.com/file/d/1UWBh7QO9PWZfp7VPfx0JADCI7Cok11-v/view?usp=sharing
**Lancier** - - https://www.lancier-monitoring.de/ - https://drive.google.com/file/d/1aszzfJh0QxT6Y1mzPlorJaci_bkmQpxy/view?usp=sharing
**Nova Service** - - - https://drive.google.com/file/d/17F6ReaVMoJRXFoOketGvvHYNhJsU2_Wa/view?usp=sharing
**ACRJ** - @acrj_oficial - https://acrj.org.br/ - https://drive.google.com/file/d/1iPu_1tzOuAI9sMuLE_n0EBWVYqWvMd3E/view?usp=sharing
**Clube de Engenharia** - @clubedeengenhariadobrasil -http://portalclubedeengenharia.org.br/ - https://drive.google.com/drive/folders/1TZL9RcvmRUUFbW4opOJcvHXDZgzQuRwe?usp=sharing
**Sebrae/RJ** - @sebraerj - https://www.sebrae.com.br/sites/PortalSebrae/ufs/rj?codUf=20 - https://drive.google.com/file/d/1l4uqd8b_zAFhRMqUsNUivfIw0rBgXML_/view?usp=sharing
**RioMed** - - http://www.riomeddistribuidora.com.br/ - https://drive.google.com/file/d/1qsGNI8HpU82a5v2lyK7e_3u3TLiygUt2/view?usp=sharing
**Sistab** -- https://sistab.com.br/ - https://drive.google.com/file/d/1OEM7TUzOK8-Fq0Ul-kF0FbDH7FWV61cG/view?usp=sharing

**Comment by yurigabrich** [comment]
Podemos definir as classificações em:

- co-organização (co-organization)
- financiamento (funding)
- parcerias (partnership)
- apoio (support)

Não sei se *financiamento* deixa claro que é apoio financeiro para ajudar o desenvolvimento do projeto, mas é totalmente diferente de *patrocínio*, que paga para participar do evento/projeto.
Dentro de financiamento também podemos incluir um link para uma página que mostra o nome de todos que contribuíram pelo crowdfunding.
