### ISSUE TITLE
Garantir que a identificação das empresas aconteça no index.html

### ISSUE THREAD

**Issue by yurigabrich** [rio-covid-19/rio-covid-19.github.io#40]
- [x] Criar o `_include > partner.html`. Referências em #6.
- [x] Linkar `partner.html` em `index.html`.
- [x] ~~Garantir que `partner.html` leia o markdown sobre as empresas, que foi definido em #38.~~

**Comment by thomascampello** [comment]
Talvez seja uma boa referencia com o source code para se basear https://learn.cloudcannon.com/jekyll/looping-in-liquid/

pasta com arquivos "md", cada arquivo com uma empresa. Usa o for para rodar todos os arquivos md dentro da pasta.

**Comment by yurigabrich** [comment]
Referência muito boa!!!

Ter 1 markdown para cada empresa vai ficar cansativo pra caramba. A estrutura é a msm q conversamos ontem. Dentro da pasta `_post` deveria ter uma pasta somente para empresas, e dentro dela estariam os arquivos `.md` relativos a cada empresa.

Mas essa referência mostra tudo de loop! Vamos tirar proveito disso, mantendo a facilidade de config do `_config.yml` \o/

Uma possibilidade:
```html

<!-- Creates the array with prefix and sufix of the variable name. -->
{% assign coord_but = "site.organizer, _button" | split: ", " %}  <!-- pay attention to blank spaces -->
{% assign coord_link = "site.organizer, _link" | split: ", " %}

<div class="coord">
  {% for stakeholder in {{ site.organizer-length }} %} <!-- This variable must be defined in the '_config.yml'. -->

    <!-- From the 'more-help.html'... I don't know if it is possible... -->
    <a href="{{ coord_link | join: forloop.index }}">{{ coord_but | join: forloop.index }} <i class='uil uil-arrow-right arrow-hover'></i></a>

  {% endfor %}
</div>
```

Espero que funcione, pois vai simplificar bastante nosso trabalho. Mesmo que o número de variáveis não seja contado automático.

**Comment by yurigabrich** [comment]
A ideia é [essa](https://github.com/rio-covid-19/rio-covid-19.github.io/issues/40#issuecomment-660063283) msm, mas está definido no lugar errado... e está com os parâmetros errados tb.

Daqui a pouco consigo ajeitar as coisas e demostro aqui como se faz.

**Comment by yurigabrich** [comment]
Exemplo de como podemos deixar a apresentação: https://startupsconnected.com.br/.
