### ISSUE TITLE
Fazer pagina "Voluntários"

### ISSUE THREAD

**Issue by thomascampello** [rio-covid-19/rio-covid-19.github.io#56]
Fazer uma primeira versão da pagina "Voluntários"

**Comment by yurigabrich** [comment]
@TCampello chegamos a conversar sobre isso em algum momento, mas já não me lembro onde, e nem quando...

Para registro, estava pensando em fazermos igual a cŕeditos de filme, pois acho q fica bem claro sobre a responsabilidade de cada um e dá para colocar uma lista grande de pessoas com uma visualização decente. Ex.:

![exemplo](https://nofilmschool.com/sites/default/files/styles/article_wide/public/end_credits.jpg?itok=XnjnRhUk)

---
E a estrutura do doc pode ser igual fizemos para os _stakeholders_ em `stakeholders.yml`. Ex.:

https://github.com/rio-covid-19/rio-covid-19.github.io/blob/69363b5a1ed92fc0852c42d2d75a80f8fe8570c8/_data/stakeholders.yml#L1-L6

**O que acha?**
