### ISSUE TITLE
Trocar slogan, pois faz referência a um app de monitoramento do corona

### ISSUE THREAD

**Issue by yurigabrich** [rio-covid-19/rio-covid-19.github.io#76]
https://github.com/rio-covid-19/rio-covid-19.github.io/blob/5fec1d414a6bdbfe47ea690e8f2597eba16619bc/_config.yml#L32

Take a look at [Juntos Contra o COVID](https://juntoscontraocovid.org/).

**Comment by Luciano25** [comment]
Slogan atualizado para "Conhecimento a serviço da sociedade"
